# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Wrapper Plugin"
  homepage: https://maven.apache.org/plugins/maven-wrapper-plugin/
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - maven-plugin
